<a href="https://colab.research.google.com/github/Mallick223/Mallick223/blob/main/exp6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

data = pd.read_excel(r'/content/drive/MyDrive/rk.xlsx')
# Drop the 'Unnamed: 0' column from the data DataFrame
data = data.drop(columns=['Unnamed: 0'])

x = data.iloc[:, :-1] # Now 'x' will correctly contain 'Age' and 'Income'
y = data.iloc[:, -1]  # Assuming the last column is the target variable
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

new_data = pd.read_excel(r'/content/drive/MyDrive/rokl.xlsx')
# 'new_data' does not contain 'Unnamed: 0', so no change needed here.
new_prediction = clf.predict(new_data)
new_data['predicted'] = new_prediction
new_data.to_excel(r'/content/drive/MyDrive/rk2.xlsx', index=False)
pd.read_excel(r'/content/drive/MyDrive/rk2.xlsx')

Accuracy:  0.5

   Age  Income predicted
0   27   40000        No
1   30   76000       Yes
2   35   80000       Yes
3   22   25000       Yes

In [33]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
k=5
knn=KNeighborsClassifier(n_neighbors=k)
knn.fit(x_train, y_train) # Train the model here

def get_float_input(prompt):
  while True:
    try:
      return float(input(prompt))
    except ValueError:
      print("Invalid input. Please enter a numeric value.")
    except KeyboardInterrupt:
      print("\nPrediction interrupted by user.")
      return None

def predict_species():
  Sepal_Length = get_float_input("Enter Sepal Length(cm): ")
  if Sepal_Length is None: return

  Sepal_Width = get_float_input("Enter Sepal Width(cm): ")
  if Sepal_Width is None: return

  Petal_Length = get_float_input("Enter Petal Length(cm): ")
  if Petal_Length is None: return

  Petal_Width = get_float_input("Enter Petal Width(cm): ")
  if Petal_Width is None: return

  input_data=np.array([[Sepal_Length,Sepal_Width,Petal_Length,Petal_Width]])
  Prediction=knn.predict(input_data)
  species_name=iris.target_names[Prediction[0]]
  print(f"\n Predicted Species: {species_name}")

predict_species()

Enter Sepal Length(cm): 4.9
Enter Sepal Width(cm): 3.0
Enter Petal Length(cm): 1.4
Enter Petal Width(cm): 0.2

 Predicted Species: setosa

In [23]:
import pandas as pd

iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
display(iris_df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

After running the above cell and following the authentication steps, your Google Drive will be mounted at `/content/drive`. You can then access your files in Drive using paths like `/content/drive/MyDrive/your_folder/your_file.xlsx`.